from django.contrib.auth.models import User
from django.db import models


class Quiz(models.Model):
    """
    Represents a quiz generated from a YouTube video.

    Each quiz belongs to a single user and is linked to the YouTube URL
    it was generated from. Title and description are AI-generated by Gemini
    but can be edited by the user via the PATCH endpoint.

    Relationships:
        user      - ForeignKey to Django's built-in User model.
                    Deleting a user cascade-deletes all their quizzes.
        questions - Reverse relation to Question (related_name='questions').
                    Accessible via quiz.questions.all().

    Fields:
        title       - Short title for the quiz (AI-generated, editable).
        description - Brief description of the quiz content (AI-generated, editable).
        video_url   - The original YouTube URL used to generate the quiz.
                      Stored as a URL string and used to embed the video in the frontend.
        created_at  - Timestamp set automatically on creation.
        updated_at  - Timestamp updated automatically on every save.
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="quizzes")
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    video_url = models.URLField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Question(models.Model):
    """
    Represents a single multiple-choice question within a quiz.

    Each question belongs to exactly one quiz. Deleting a quiz
    cascade-deletes all its associated questions.

    Fields:
        quiz             - ForeignKey to the parent Quiz.
                           Deleting a quiz cascade-deletes all its questions.
        question_title   - The question text (e.g. 'What is the capital of France?').
        question_options - A JSON array of exactly 4 answer choices.
                           Example: ["Paris", "London", "Berlin", "Madrid"]
                           Stored as JSONField to avoid a separate Option model.
        answer           - The correct answer. Must exactly match one of the values
                           in question_options to ensure frontend comparison works.
        created_at       - Timestamp set automatically on creation.
        updated_at       - Timestamp updated automatically on every save.
    """

    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name="questions")
    question_title = models.CharField(max_length=500)
    question_options = models.JSONField()
    answer = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question_title